Repository LedgerHQ/ledger-live-mobile, pull requests merged in 2020-08, with the labels that each got.

#1336 Addresses strandhogg v1/v2 vuln
  android/app/src/main/AndroidManifest.xml
Labels: important

#1333 LL-2823 (OperationDetails): operation type added to header title
  src/components/RootNavigator/BaseNavigator.js
Labels: QA

#1332 LL-2875 (Cosmos): wording updates
  src/locales/en/common.json
Labels: QA

#1329 LL-2842 Deep Link
  README.md
  android/app/src/main/AndroidManifest.xml
  deep-links-test-page.html
  ios/ledgerlivemobile/Info.plist
  package.json
  src/components/FilteredSearchBar.js
  src/components/RootNavigator/index.js
  src/index.js
  src/screens/Accounts/index.js
  src/screens/Exchange/SelectCurrency.js
  src/screens/ReceiveFunds/01-SelectAccount.js
  src/screens/SendFunds/01-SelectAccount.js
  yarn.lock
Labels: QA, important

#1338 add manager provider to experimental settings
  ios/Podfile.lock
  src/experimental.js
  src/screens/Settings/Experimental/FeatureInteger.js
  src/screens/Settings/Experimental/FeatureRow.js
  src/screens/Settings/Experimental/index.js
  src/screens/Settings/General/BiometricsRow.js
Labels: important

#1331 LL-2775 (Fonts): updated fonts to Inter family
  android/app/src/main/assets/fonts/Feather.ttf
  android/app/src/main/assets/fonts/Fontisto.ttf
  android/app/src/main/assets/fonts/Inter-Bold.otf
  android/app/src/main/assets/fonts/Inter-Regular.otf
  android/app/src/main/assets/fonts/Inter-SemiBold.otf
  android/app/src/main/assets/fonts/MaterialCommunityIcons.ttf
  assets/fonts/Inter-Bold.otf
  assets/fonts/Inter-Regular.otf
  assets/fonts/Inter-SemiBold.otf
  assets/fonts/MuseoSans-Bold.otf
  assets/fonts/MuseoSans-Regular.otf
  assets/fonts/MuseoSans-SemiBold.otf
  assets/fonts/OpenSans-Bold.ttf
  assets/fonts/OpenSans-Regular.ttf
  assets/fonts/OpenSans-SemiBold.ttf
  assets/fonts/Rubik-Regular.ttf
  ios/ledgerlivemobile.xcodeproj/project.pbxproj
  ios/ledgerlivemobile/Info.plist
  src/components/AccountCard.js
  src/components/AccountDistribution/Row.js
  src/components/AccountGraphCard.js
  src/components/AssetGraphCard.js
  src/components/BulletList.js
  src/components/CameraScreen/QRCodeProgressBar.js
  src/components/CurrencyRate.js
  src/components/DelegationDrawer.js
  src/components/Delta.js
  src/components/FirmwareProgress.js
  src/components/GraphCard.js
  src/components/LText/getFontStyle.android.js
  src/components/LText/getFontStyle.ios.js
  src/components/LText/index.js
  src/components/OperationRow.js
  src/components/SelectableAccountsList.js
  src/components/SubAccountRow.js
  src/components/ValidateOnDeviceDataRow.js
  src/families/bitcoin/BitcoinFeePerByteRow.js
  src/families/cosmos/ClaimRewardsFlow/02-SelectMethod.js
  src/families/cosmos/Delegations/index.js
  src/families/ethereum/EditFeeUnitEthereum.js
  src/families/tezos/AccountBodyHeader.js
  src/families/tezos/DelegationDetailsModal.js
  src/families/tezos/DelegationFlow/SelectValidator.js
  src/families/tezos/DelegationFlow/Summary.js
  src/families/tron/operationDetails.js
  src/locales/en/common.json
  src/screens/Account/ListHeaderComponent.js
  src/screens/Accounts/AccountRow.js
  src/screens/Asset/index.js
  src/screens/Distribution/DistributionCard.js
  src/screens/Distribution/index.js
  src/screens/OperationDetails/Content.js
  src/screens/Portfolio/BalanceHeader.js
  src/screens/SendFunds/03-Amount.js
  src/screens/SendFunds/AmountInput.js
  src/screens/SendFunds/SummaryAmountSection.js
  src/screens/Settings/Accounts/TokenContextualModal.js
  src/screens/Settings/CryptoAssets/Currencies/CurrencySettings.js
Labels: QA

#1347 use erc20 unit when available in validation screen
  src/components/ValidateOnDevice.js
Labels: important

#1346 LL-2778 Hide portfolio's sticky header if placeholder
  src/screens/Portfolio/index.js
Labels: QA

#1350 LL-3056 (DeviceAction): update receive address flow
  src/components/DeviceJob/steps.js
  src/screens/ReceiveFunds/03-Confirmation.js
Labels: important

#1352 bump libcore version
  package.json
  src/families/algorand/Rewards/index.js
  src/locales/en/common.json
  yarn.lock
Labels: important
