Repository LedgerHQ/ledger-live-mobile, pull requests merged in 2020-09, with the labels that each got.

#1375 bump libcore bindings 4.15.12
  package.json
  yarn.lock
Labels: important

#1379 bump libcore v4.15.13
  package.json
  yarn.lock
Labels: important

#1380 bump live-common
  ios/Podfile.lock
  ios/ledgerlivemobile.xcodeproj/project.pbxproj
  package.json
  scripts/post.sh
  yarn.lock
Labels: important

#1363 (Algo): send fees summary unit updated with correct value for ASA
  src/families/algorand/SendRowsFee.js
Labels: important

#1365 LL-2877 Cosmos polish
  src/families/cosmos/AccountBalanceSummaryFooter.js
Labels: important

#1382 LL-3128 (Manager): change add tokens wording
  src/locales/en/common.json
  src/screens/Manager/Modals/SearchModal.js
Labels: QA

#1373 LL-1927 (AccountDistribution): navigation issue fixed
  src/components/AccountDistribution/Row.js
  src/components/RootNavigator/BaseNavigator.js
Labels: QA

#1383 LL-3100 (ETH): summary gas price and max fees updated
  src/families/ethereum/EthereumFeeRow.js
  src/families/ethereum/ScreenEditFee.js
  src/locales/en/common.json
Labels: QA

#1384 update libs
  ios/Podfile.lock
  ios/ledgerlivemobile.xcodeproj/project.pbxproj
  package.json
  yarn.lock
Labels: important

#1385 Fixes iOS crashes (optimistically)
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: important

#1377 LL-2976 Manager + Onboarding Device actions
  src/animations/nanoX/bluetooth/5AllowManager/dark.html
  src/animations/nanoX/bluetooth/5AllowManager/dark.json
  src/animations/nanoX/bluetooth/5AllowManager/light.html
  src/animations/nanoX/bluetooth/5AllowManager/light.json
  src/components/SelectDevice/index.js
  src/components/SelectDevice/legacy.js
  src/locales/en/common.json
  src/screens/Manager/Manager.js
  src/screens/Manager/index.js
  src/screens/Onboarding/steps/pair-new.js
Labels: important

#1343 Fix debug screens + drop unused + Improvements to Debug Store
  package.json
  scripts/debugsvg.sh
  src/components/RootNavigator/SettingsNavigator.js
  src/const/navigation.js
  src/reducers/accounts.js
  src/reducers/index.js
  src/reducers/settings.js
  src/screens/AddAccounts/AddAccountsModal.js
  src/screens/DebugBLE.js
  src/screens/DebugPlayground.js
  src/screens/DebugSVG.js
  src/screens/DebugStore.js
  src/screens/DebugWSImport.js
  src/screens/Settings/Debug/OpenDebugPlayground.js
  src/screens/Settings/Debug/index.js
Labels: QA

#1387 Revert "Merge pull request #1377 from LFBarreto/LL-2976"
  src/animations/nanoX/bluetooth/5AllowManager/dark.html
  src/animations/nanoX/bluetooth/5AllowManager/dark.json
  src/animations/nanoX/bluetooth/5AllowManager/light.html
  src/animations/nanoX/bluetooth/5AllowManager/light.json
  src/components/SelectDevice/index.js
  src/components/SelectDevice/legacy.js
  src/locales/en/common.json
  src/screens/Manager/Manager.js
  src/screens/Manager/index.js
  src/screens/Onboarding/steps/pair-new.js
Labels: important

#1390 LL-3459 Fix ERC20 unit on tx verification screen
  src/screens/ConnectDevice.js
  src/screens/SendFunds/04-Summary.js
Labels: QA, important

#1391 @ledgerhq/cryptoassets
  package.json
  src/live-common-setup.js
  src/screens/MigrateAccounts/01-Overview.js
  src/screens/Settings/Accounts/index.js
  yarn.lock
Labels: important

#1381 LL-3173 (AccountPage): Group acount cta in one button drawer
  src/families/tron/accountActions.js
  src/icons/MoreHorizontal.js
  src/screens/Account/AccountActions.js
Labels: important
