Repository LedgerHQ/ledger-live-mobile, pull requests merged in 2020-01, with the labels that each got.

#1130 Update live common 11
  ios/Podfile.lock
  package.json
  scripts/RCTCoreOperationQuery.java.patch
  scripts/post.sh
  src/bridge/BridgeSyncContext.js
  src/index.js
  src/logic/screenTransactionHooks.js
  src/screens/AddAccounts/03-Accounts.js
  src/screens/MigrateAccounts/03-Progress.js
  yarn.lock
Labels: important

#1138 Common + core bumps
  ios/Podfile.lock
  package.json
  src/screens/Distribution/index.js
  yarn.lock
Labels: important

#1140 LL-2112 react native hid version 5.6.0 -> 5.6.2
  package.json
  src/screens/Distribution/index.js
  src/screens/Settings/CryptoAssets/Currencies/CurrencySettings.js
  yarn.lock
Labels: bug

#1135 ERC20 operation details: Back arrow icon is missing
  src/components/OperationRow.js
  src/screens/OperationDetails/index.js
Labels: UX / UI

#1141 update live-common@11.3.0
  ios/Podfile.lock
  package.json
  src/components/AccountDistribution/Row.js
  src/screens/Asset/index.js
  src/screens/ReceiveFunds/01-SelectAccount.js
  yarn.lock
Labels: important
