Repository LedgerHQ/ledger-live-mobile, pull requests merged in 2020-11, with the labels that each got.

#1432 live-common 15.7.0
  package.json
  src/experimental.js
  src/screens/Onboarding/steps/pair-new.js
  yarn.lock
Labels: important

#1438 (Lending): fix ui
  src/components/DelegationDrawer.js
  src/families/ethereum/operationDetails.js
  src/icons/OperationStatusIcon/Enable.js
  src/icons/OperationStatusIcon/Supply.js
  src/icons/OperationStatusIcon/Withdraw.js
  src/icons/OperationStatusIcon/index.js
  src/icons/Withdraw.js
  src/locales/en/common.json
  src/logic/screenTransactionHooks.js
  src/screens/Account/hooks/useLendingActions.js
  src/screens/Lending/Account/AccountBodyHeader.js
  src/screens/Lending/ClosedLoans/ClosedLoansRow.js
  src/screens/Lending/Dashboard/ActiveAccountRow.js
  src/screens/Lending/Dashboard/ActiveAccounts.js
  src/screens/Lending/Dashboard/index.js
  src/screens/Lending/EnableFlow/04-ValidationError.js
  src/screens/Lending/EnableFlow/04-ValidationSuccess.js
  src/screens/Lending/SupplyFlow/03-ValidationError.js
  src/screens/Lending/SupplyFlow/03-ValidationSuccess.js
  src/screens/Lending/WithdrawFlow/03-ValidationError.js
  src/screens/Lending/WithdrawFlow/03-ValidationSuccess.js
  src/screens/Lending/modals/BaseModal.js
Labels: QA, important

#1439 update carousel nonce
  src/components/Carousel/index.js
Labels: QA

#1430 LL-2766 – wording change on countervalue
  src/locales/en/common.json
Labels: QA

#1337 upgrade dependencies
  .flowconfig
  .gitattributes
  android/app/_BUCK
  android/app/build.gradle
  android/app/src/debug/java/com/ledger/live/ReactNativeFlipper.java
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/ledger/live/MainApplication.java
  android/build.gradle
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.jar
  android/gradle/wrapper/gradle-wrapper.properties
  android/gradlew
  android/gradlew.bat
  ios/Podfile
  ios/Podfile.lock
  ios/ledgerlivemobile.xcodeproj/project.pbxproj
  ios/ledgerlivemobile.xcodeproj/xcshareddata/xcschemes/ledgerlivemobile.xcscheme
  ios/ledgerlivemobile/AppDelegate.h
  ios/ledgerlivemobile/AppDelegate.m
  ios/ledgerlivemobile/main.m
  ios/ledgerlivemobileTests/ledgerlivemobileTests.m
  package.json
  scripts/RNAnalyticsModule.kt
  scripts/post.sh
  src/components/Carousel/slides/BackupPack.js
  src/components/Carousel/slides/BuyCrypto.js
  src/components/Carousel/slides/LedgerAcademy.js
  src/components/Carousel/slides/Lending.js
  src/components/Carousel/slides/Sell.js
  src/components/Carousel/slides/StakeAlgo.js
  src/components/Carousel/slides/StakeCosmos.js
  src/components/Carousel/slides/Swap.js
  src/components/Carousel/slides/Vote.js
  src/polyfill.js
  src/screens/Onboarding/OnboardingLayout.js
  yarn.lock
Labels: QA, important

#1445 2.16.0 remaining work to QA
  package.json
  src/components/ValidateOnDevice.js
  src/components/banners/OngoingScams.js
  src/config/urls.js
  src/locales/en/common.json
  src/screens/Lending/EnableFlow/02-Amount/Advanced.js
  src/screens/Lending/EnableFlow/02-Amount/index.js
  src/screens/Lending/EnableFlow/04-ValidationSuccess.js
  src/screens/Lending/SupplyFlow/03-ValidationSuccess.js
  src/screens/Lending/WithdrawFlow/03-ValidationSuccess.js
  src/screens/Portfolio/index.js
  yarn.lock
Labels: important

#1443 fix compound v2
  src/components/ValidateOnDevice.js
  src/locales/en/common.json
  src/screens/Lending/EnableFlow/02-Amount/Advanced.js
  src/screens/Lending/EnableFlow/02-Amount/index.js
  src/screens/Lending/EnableFlow/04-ValidationSuccess.js
  src/screens/Lending/SupplyFlow/03-ValidationSuccess.js
  src/screens/Lending/WithdrawFlow/03-ValidationSuccess.js
Labels: HODL, QA, important

#1433 LL-3775 Add a warning banner for ongoing scam campaigns
  src/components/banners/OngoingScams.js
  src/config/urls.js
  src/locales/en/common.json
  src/screens/Portfolio/index.js
Labels: HODL, QA, important

#1424 LL-3679 Make settings/accounts navigators go to first screen on blur
  src/components/RootNavigator/MainNavigator.js
Labels: QA

#1451 live-common 15.8.0
  package.json
  yarn.lock
Labels: QA, important

#1440 LL3633 black friday banner
  src/components/Carousel/index.js
  src/components/Carousel/slides/BlackFriday.js
  src/config/urls.js
  src/images/banners/blackfriday.png
  src/images/banners/lending.png
  src/locales/en/common.json
Labels: QA

#1442 Bring back the sticky header on portfolio
  src/screens/Portfolio/index.js
Labels: QA

#1436 LL-3770 update buyNanoX url
  src/config/urls.js
Labels: QA

#1450 LL-3037 (Cosmos): update support urls
  src/families/cosmos/DelegationFlow/01-Started.js
Labels: QA

#1448 LL-3666 (DiscreetMode): add toggle for discreet mode
  src/actions/settings.js
  src/components/AccountGraphCard.js
  src/components/AssetGraphCard.js
  src/components/CurrencyUnitValue.js
  src/components/Delta.js
  src/components/DiscreetModeButton.js
  src/components/GraphCard.js
  src/families/algorand/operationDetails.js
  src/families/cosmos/operationDetails.js
  src/families/tron/operationDetails.js
  src/icons/ArrowDown.js
  src/icons/ArrowUp.js
  src/icons/Eye.js
  src/icons/EyeCrossed.js
  src/reducers/settings.js
  src/screens/Account/LendingBanners.js
  src/screens/Account/ListHeaderComponent.js
  src/screens/Asset/index.js
  src/screens/Lending/EnableFlow/01-SelectAccount.js
  src/screens/Lending/EnableFlow/02-Amount/index.js
Labels: QA

#1434 add paste cta and verify address info box
  src/icons/Paste.js
  src/locales/en/common.json
  src/screens/SendFunds/02-SelectRecipient.js
Labels: QA

#1446 add carousel click events
  src/components/Carousel/slides/BackupPack.js
  src/components/Carousel/slides/BuyCrypto.js
  src/components/Carousel/slides/LedgerAcademy.js
  src/components/Carousel/slides/Lending.js
  src/components/Carousel/slides/Sell.js
  src/components/Carousel/slides/StakeAlgo.js
  src/components/Carousel/slides/StakeCosmos.js
  src/components/Carousel/slides/Swap.js
  src/components/Carousel/slides/Vote.js
Labels: QA

#1454 remove BCH warnings
  src/components/CurrencyDownStatusAlert.js
  src/config/urls.js
  src/locales/en/common.json
Labels: QA

#1460 fix black banner
  src/components/Carousel/slides/BlackFriday.js
Labels: important

#1459 LL-3906 Graph balance font issue
  src/components/AccountGraphCard.js
  src/components/AssetGraphCard.js
  src/components/CurrencyUnitValue.js
  src/components/Delta.js
  src/components/GraphCard.js
  src/screens/Account/ListHeaderComponent.js
  src/screens/Asset/index.js
Labels: important

#1410 LL-2135 Integrate new CounterValues API
  .flowconfig
  .gitignore
  package.json
  src/actions/general.js
  src/actions/portfolio.js
  src/components/AccountDistribution/Row.js
  src/components/AccountDistribution/index.js
  src/components/CounterValue.js
  src/components/CounterValuesProvider.js
  src/components/DBSave.js
  src/components/RefreshAccountOrdering.js
  src/components/RootNavigator/CryptoAssetsSettingsNavigator.js
  src/components/RootNavigator/SettingsNavigator.js
  src/components/SyncIndicator.js
  src/components/SyncIndicatorConnector.js
  src/components/SyncIndicatorError.js
  src/components/SyncIndicatorLoading.js
  src/components/SyncIndicatorStatus.js
  src/components/accountSyncRefreshControl.js
  src/components/globalSyncRefreshControl.js
  src/const/navigation.js
  src/context/LedgerStore.js
  src/context/Reboot.js
  src/countervalues.js
  src/cryptocurrencies.js
  src/db.js
  src/index.js
  src/locales/en/common.json
  src/reducers/index.js
  src/screens/Account/ListHeaderComponent.js
  src/screens/Account/index.js
  src/screens/Accounts/AccountOrder.js
  src/screens/Accounts/OrderOption.js
  src/screens/AddAccounts/01-SelectCrypto.js
  src/screens/Asset/index.js
  src/screens/Distribution/index.js
  src/screens/Exchange/SelectCurrency.js
  src/screens/Lending/ClosedLoans/index.js
  src/screens/Lending/Dashboard/index.js
  src/screens/Lending/History/index.js
  src/screens/Portfolio/index.js
  src/screens/SendFunds/03-Amount.js
  src/screens/SendFunds/AmountInput.js
  src/screens/Settings/CryptoAssets/Rates/Price.js
  src/screens/Settings/CryptoAssets/Rates/RateProviderSettings.js
  src/screens/Settings/CryptoAssets/Rates/RatesList.js
  src/screens/Settings/Debug/GenerateMockAccounts.js
  src/screens/Settings/Help/ClearCacheRow.js
  src/screens/Settings/Help/HardResetRow.js
  yarn.lock
Labels: QA, important

#1468 live-common 17.0.0
  package.json
  src/experimental.js
  yarn.lock
Labels: important

#1472 Fix Lending screen
  package.json
  src/components/RootNavigator/LendingNavigator.js
  src/screens/Lending/History/index.js
  src/screens/Lending/useCompoundSummaries.js
  yarn.lock
Labels: QA

#1465 LL-3878 fix balance in first step of send flow
  src/components/AccountCard.js
Labels: QA

#1470 AnalyticsConsole, debugging tool for tracked events
  src/analytics/HookAnalytics.js
  src/analytics/segment.js
  src/components/AnalyticsConsole.js
  src/components/RootNavigator/MainNavigator.js
  src/index.js
  src/screens/Onboarding/steps/welcome.js
  src/screens/Settings/Debug/AnalyticsConsoleRow.js
  src/screens/Settings/Debug/index.js
  src/screens/Settings/PoweredByLedger.js
  src/screens/Settings/index.js
Labels: QA

#1441 LL-3609 Better flow when accessing manager from Swap with query/tab
  src/components/DeviceActionModal.js
  src/components/RootNavigator/MainNavigator.js
  src/screens/Manager/AppsList/AppUpdateAll.js
  src/screens/Manager/AppsScreen.js
  src/screens/Manager/Manager.js
  src/screens/Manager/index.js
  src/screens/Swap/Form/SelectAccount/BadSelectionModal.js
  src/screens/Swap/MissingOrOutdatedSwapApp.js
  yarn.lock
Labels: QA
