Repository LedgerHQ/ledger-live-mobile, pull requests merged in 2020-10, with the labels that each got.

#1388 LL-2976 Manager Device actions
  src/animations/nanoX/bluetooth/5AllowManager/dark.html
  src/animations/nanoX/bluetooth/5AllowManager/dark.json
  src/animations/nanoX/bluetooth/5AllowManager/light.html
  src/animations/nanoX/bluetooth/5AllowManager/light.json
  src/components/SelectDevice/index.js
  src/components/SelectDevice/legacy.js
  src/locales/en/common.json
  src/screens/Manager/Manager.js
  src/screens/Manager/index.js
  src/screens/Onboarding/steps/pair-new.js
Labels: QA, important

#1386 LL-3387 (Storage): increase operation retention storage from 100 -> 500
  src/logic/accountModel.js
Labels: QA

#1393 LL-3116 Use the 'clearAccount' helper for CLEAN_CACHE
  src/reducers/accounts.js
Labels: QA

#1392 Spin loading indicator clockwise
  src/components/DeviceAction/rendering.js
Labels: QA

#1348 Swap
  .gitignore
  ios/Podfile.lock
  ios/ledgerlivemobile.xcodeproj/project.pbxproj
  package.json
  src/actions/settings.js
  src/components/CircleCurrencyIcon.js
  src/components/CountdownTimer.js
  src/components/CurrencyRow.js
  src/components/DeviceAction/index.js
  src/components/DeviceAction/rendering.js
  src/components/DeviceJob/steps.js
  src/components/ErrorIcon.js
  src/components/ExternalLink.js
  src/components/InfoBox.js
  src/components/RootNavigator/BaseNavigator.js
  src/components/RootNavigator/SwapNavigator.js
  src/components/SectionSeparator.js
  src/components/SelectDevice/index.js
  src/components/useBroadcast.js
  src/components/useInterval.js
  src/config/urls.js
  src/const/navigation.js
  src/icons/Donjon.js
  src/icons/DownloadFile.js
  src/icons/Swap.js
  src/images/swap.png
  src/locales/en/common.json
  src/modals/Create.js
  src/reducers/settings.js
  src/screens/Account/AccountActions.js
  src/screens/Account/AccountActionsDefault.js
  src/screens/Swap/Confirmation.js
  src/screens/Swap/Connect.js
  src/screens/Swap/Form/Amount.js
  src/screens/Swap/Form/DisclaimerModal.js
  src/screens/Swap/Form/Error.js
  src/screens/Swap/Form/PendingOperation.js
  src/screens/Swap/Form/SelectAccount/01-SelectCrypto.js
  src/screens/Swap/Form/SelectAccount/02-SelectAccount.js
  src/screens/Swap/Form/SelectAccount/BadSelectionModal.js
  src/screens/Swap/Form/SelectAccount/NoAccountsEmptyState.js
  src/screens/Swap/Form/Summary/SummaryBody.js
  src/screens/Swap/Form/Summary/index.js
  src/screens/Swap/Form/index.js
  src/screens/Swap/FormOrHistory.js
  src/screens/Swap/History/EmptyState.js
  src/screens/Swap/History/OperationRow.js
  src/screens/Swap/History/index.js
  src/screens/Swap/Landing.js
  src/screens/Swap/MissingOrOutdatedSwapApp.js
  src/screens/Swap/NotAvailable.js
  src/screens/Swap/OperationDetails.js
  src/screens/Swap/Swap.js
  src/screens/Swap/SwapStatusIndicator.js
  yarn.lock
Labels: QA

#1396 LL-3568 Swap - Allow the destination account to be selected before the source
  src/screens/Swap/Form/SelectAccount/01-SelectCrypto.js
Labels: QA

#1395 Bump live-common, add wording for newly split swap rate error
  package.json
  src/locales/en/common.json
  yarn.lock
Labels: QA

#1401 Swap - Grouped fixes for the release
  package.json
  src/components/banners/SwapBanner.js
  src/locales/en/common.json
  src/screens/Portfolio/index.js
  src/screens/Swap/Confirmation.js
  src/screens/Swap/Form/PendingOperation.js
  src/screens/Swap/Form/SelectAccount/01-SelectCrypto.js
  src/screens/Swap/Form/SelectAccount/02-SelectAccount.js
  src/screens/Swap/Form/SelectAccount/BadSelectionModal.js
  src/screens/Swap/Form/Summary/SummaryBody.js
  src/screens/Swap/FormOrHistory.js
  src/screens/Swap/History/index.js
  src/screens/Swap/Landing.js
  src/screens/Swap/OperationDetails.js
  src/screens/Swap/SwapStatusIndicator.js
  yarn.lock
Labels: QA, important

#1398 LL-3429 (Manager): added searchQuery param to navigation flow
  src/screens/Manager/AppsScreen.js
  src/screens/Manager/Manager.js
  src/screens/Manager/Modals/SearchModal.js
  src/screens/Manager/index.js
  src/screens/Portfolio/EmptyStatePortfolio.js
  src/screens/Swap/Form/SelectAccount/BadSelectionModal.js
  src/screens/Swap/MissingOrOutdatedSwapApp.js
Labels: QA

#1406 LL-3363 Fix for experimental device action being active by default
  package.json
  src/components/DeviceAction/index.js
  src/locales/en/common.json
  yarn.lock
Labels: QA, important

#1405 LL-3551 Analytics track currency name on add account flow
  src/screens/AddAccounts/02-SelectDevice.js
  src/screens/AddAccounts/02-TokenCurrencyDisclaimer.js
  src/screens/AddAccounts/03-Accounts.js
  src/screens/AddAccounts/04-Success.js
Labels: QA

#1412 EthJS
  package.json
  src/bridge/cache.js
  src/experimental.js
  yarn.lock
Labels: important

#1413 Blind fix for swap op details erc20 crash
  src/screens/Swap/OperationDetails.js
Labels: important

#1415 add implicitMigration
  package.json
  src/actions/accounts.js
  yarn.lock
Labels: important

#1414 Add BCH hardfork warning banner
  src/components/CurrencyDownStatusAlert.js
  src/components/ExternalLink.js
  src/components/WarningBanner.js
  src/config/urls.js
  src/locales/en/common.json
  src/screens/Portfolio/GraphCardContainer.js
  src/screens/Portfolio/index.js
Labels: QA, important

#1427 Fixes access of receive flow from an account
  src/reducers/accounts.js
  src/screens/ReceiveFunds/02-ConnectDevice.js
  src/screens/ReceiveFunds/03-Confirmation.js
Labels: important, regression

#1426 Ethjs enabled in production
  package.json
  src/experimental.js
  src/families/ethereum/EditFeeUnitEthereum.js
  src/screens/OperationDetails/Content.js
  src/screens/Portfolio/index.js
  yarn.lock
Labels: important
