Repository LedgerHQ/ledger-live-mobile, pull requests merged in 2020-12, with the labels that each got.

#1474 LL-3877 add buy/receive info drawer on lending dashboard
  src/locales/en/common.json
  src/screens/Lending/Dashboard/InfoModalBottom.js
  src/screens/Lending/Dashboard/Rates.js
Labels: QA

#1477 LL-3860 Wording changes, lots of wording changes
  src/config/urls.js
  src/locales/en/common.json
Labels: QA

#1458 TAC modal onClick only on link
  src/components/CheckBox.js
  src/locales/en/common.json
  src/screens/Lending/modals/InfoModals/TermsStep.js
Labels: QA

#1478 LL-3940 (Lending): removal of eth high fees modal
  src/screens/Lending/shared/LendingWarnings.js
Labels: QA

#1467 added utms on all URL
  src/config/urls.js
Labels: QA

#1480 Bump live-common, fix on spendableBalance for child accounts
  package.json
  src/components/AccountCard.js
  yarn.lock
Labels: QA, important

#1481 LL-3937 Bring back the pull to refresh to portfolio
  src/screens/Portfolio/index.js
Labels: HODL

#1490 Live common 17 3 x
  package.json
  src/locales/en/common.json
  yarn.lock
Labels: QA, important

#1492 Revert powered by ledger debug access
  src/components/RootNavigator/MainNavigator.js
  src/config/urls.js
  src/screens/Onboarding/steps/welcome.js
  src/screens/Settings/PoweredByLedger.js
  src/screens/Settings/index.js
Labels: QA, important

#1489 add a utxo warning when utxo > 50
  src/locales/en/common.json
  src/screens/SendFunds/04-Summary.js
  src/screens/SendFunds/TooMuchUTXOBottomModal.js
Labels: QA

#1494 Bring back the scroll to top on bottom tab navigation double tap
  src/navigation/utils.js
Labels: QA

#1503 Fixes XRP send
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: QA, important

#1508 Onboarding polish
  src/components/ConfirmationModal.js
  src/components/OnboardingStepperView/OnboardingStepView.js
  src/components/OnboardingStepperView/index.js
  src/screens/Onboarding/OnboardingQuiz.js
  src/screens/Onboarding/assets/setupDeviceSlide_1.png
  src/screens/Onboarding/assets/setupDeviceSlide_5.png
  src/screens/Onboarding/steps/language.js
  src/screens/Onboarding/steps/newDeviceInfo.js
  src/screens/Onboarding/steps/welcome.js
Labels: QA

#1511 Mashup PR for 2.19 requirements
  ios/Podfile.lock
  package.json
  src/bridge/cache.js
  src/components/CopyLink.js
  src/index.js
  src/languages.js
  src/screens/Onboarding/steps/welcome.js
  src/screens/SendFunds/02-SelectRecipient.js
  src/screens/Settings/General/index.js
  src/screens/SignMessage/03-ConnectDevice.js
  src/screens/WalletConnect/Connect.js
  src/screens/WalletConnect/Provider.js
  src/screens/WalletConnect/Scan.js
  yarn.lock
Labels: important

#1513 LL-4248 (Onboarding): term checkboxs wording updated
  src/config/urls.js
  src/locales/en/common.json
  src/screens/Onboarding/steps/terms.js
Labels: important

#1518 pass correct remote when pushing android tags
  fastlane/Fastfile
Labels: QA
