Repository LedgerHQ/ledger-live-mobile, pull requests merged in 2021-02, with the labels that each got.

#1570 Live common 18.3.x
  package.json
  src/components/CameraScreen/QRCodeBottomLayer.js
  src/components/InfoBox.js
  src/components/PasswordInput.js
  src/components/Switch.js
  src/context/AuthPass/AuthScreen.js
  src/index.js
  src/locales/en/common.json
  src/screens/Onboarding/shared/infoPagesData.js
  src/screens/SendFunds/04-Summary.js
  src/screens/SendFunds/AmountInput.js
  src/screens/Settings/PoweredByLedger.js
  yarn.lock
Labels: important

#1571 LL-4388 Styling fix for iOS monospace unicode on 𝚝BTC
  src/components/AccountGraphCard.js
  src/components/AssetGraphCard.js
  src/screens/Account/ListHeaderComponent.js
  src/screens/Asset/index.js
Labels: QA

#1500 [Coin-integration] Polkadot
  package.json
  src/config/urls.js
  src/const/navigation.js
  src/families/helpers.js
  src/families/index.js
  src/families/polkadot/AccountBalanceSummaryFooter.js
  src/families/polkadot/AccountBodyHeader.js
  src/families/polkadot/BondFlow/01-Started.js
  src/families/polkadot/BondFlow/02-Amount.js
  src/families/polkadot/BondFlow/04-ValidationError.js
  src/families/polkadot/BondFlow/04-ValidationSuccess.js
  src/families/polkadot/BondFlow/index.js
  src/families/polkadot/NominateFlow/01-Validators.js
  src/families/polkadot/NominateFlow/03-ValidationError.js
  src/families/polkadot/NominateFlow/03-ValidationSuccess.js
  src/families/polkadot/NominateFlow/ValidatorItem.js
  src/families/polkadot/NominateFlow/drawerInfo.js
  src/families/polkadot/NominateFlow/index.js
  src/families/polkadot/Nominations/Actions.js
  src/families/polkadot/Nominations/NominationRow.js
  src/families/polkadot/Nominations/UnlockingRow.js
  src/families/polkadot/Nominations/UnsupportedWarning.js
  src/families/polkadot/Nominations/drawerInfo.js
  src/families/polkadot/Nominations/index.js
  src/families/polkadot/RebondFlow/01-Amount.js
  src/families/polkadot/RebondFlow/03-ValidationError.js
  src/families/polkadot/RebondFlow/03-ValidationSuccess.js
  src/families/polkadot/RebondFlow/index.js
  src/families/polkadot/SendRowsFee.js
  src/families/polkadot/SimpleOperationFlow/01-Started.js
  src/families/polkadot/SimpleOperationFlow/03-ValidationError.js
  src/families/polkadot/SimpleOperationFlow/03-ValidationSuccess.js
  src/families/polkadot/SimpleOperationFlow/index.js
  src/families/polkadot/TransactionConfirmFields.js
  src/families/polkadot/UnbondFlow/01-Amount.js
  src/families/polkadot/UnbondFlow/03-ValidationError.js
  src/families/polkadot/UnbondFlow/03-ValidationSuccess.js
  src/families/polkadot/UnbondFlow/index.js
  src/families/polkadot/accountActions.js
  src/families/polkadot/components/CollapsibleList.js
  src/families/polkadot/components/FlowErrorBottomModal.js
  src/families/polkadot/components/NominationDrawer.js
  src/families/polkadot/components/NominationInfo.js
  src/families/polkadot/index.js
  src/families/polkadot/operationDetails.js
  src/icons/Coins.js
  src/icons/VoteNay.js
  src/locales/en/common.json
  src/locales/fr/common.json
  yarn.lock
Labels: QA, important

#1574 LL-4532 Remove backup pack banner
  src/components/Carousel/index.js
Labels: QA, important

#1563 LL-4449 Fix chart y-axis rendering
  src/components/AccountGraphCard.js
  src/components/AssetGraphCard.js
  src/components/Graph/index.js
  src/components/GraphCard.js
Labels: QA, important

#1539 updated coinify buy api to v2
  src/screens/Exchange/CoinifyWidget.js
Labels: QA, important

#1517 skipDevice flow on buy
  src/components/DangerBox.js
  src/icons/ShieldAlt.js
  src/locales/en/common.json
  src/screens/Exchange/CoinifyWidget.js
  src/screens/Exchange/CoinifyWidgetScreen.js
  src/screens/Exchange/ConnectDevice.js
  src/screens/Exchange/SkipDeviceVerification.js
Labels: QA, important

#1560 LL-4237 display full balance on add account selection
  Gemfile.lock
  ios/Podfile.lock
  src/components/AccountCard.js
  src/components/SelectableAccountsList.js
  src/screens/AddAccounts/03-Accounts.js
Labels: QA

#1591 LL-4578 (ImportDesktopSettings): dev mode by default issue
  src/reducers/settings.js
  src/screens/Portfolio/index.js
  src/screens/Settings/Experimental/ExperimentalHeader.js
Labels: QA, important

#1579 live-common 18.4.x
  ios/Podfile.lock
  package.json
  src/components/CurrencyDownStatusAlert.js
  src/config/urls.js
  src/live-common-setup.js
  src/locales/en/common.json
  src/locales/es/common.json
  src/locales/fr/common.json
  src/locales/ja/common.json
  src/locales/ko/common.json
  src/locales/ru/common.json
  src/locales/zh/common.json
  yarn.lock
Labels: QA, important

#1564 LL-4450 Bring back blur on app switcher iOS
  ios/ledgerlivemobile/AppDelegate.m
Labels: QA

#1565 LL-4292 LL-4456 (Onboarding): bullet text line height updated
  src/components/OnboardingStepperView/OnboardingInfoModal.js
  src/components/OnboardingStepperView/OnboardingStepView.js
Labels: QA

#1566 LL-4378 (Button): fix loader animation on send flow
  src/components/Button.js
  src/families/tezos/DelegationFlow/Summary.js
  src/screens/SendFunds/02-SelectRecipient.js
  src/screens/SendFunds/04-Summary.js
Labels: QA

#1584 LL-4293 fix typo on onboarding
  src/locales/en/common.json
Labels: QA

#1595 Mashup 2021 feb 16
  TERMS.es.md
  TERMS.fr.md
  ios/Podfile.lock
  package.json
  src/analytics/HookAnalytics.js
  src/analytics/segment.js
  src/colors.js
  src/components/AnimatedHeader.js
  src/components/ExternalLink.js
  src/components/GenericErrorView.js
  src/components/InfoBox.js
  src/components/NavBarColorHandler.android.js
  src/components/NavBarColorHandler.ios.js
  src/components/OnboardingStepperView/OnboardingInfoModal.js
  src/components/OnboardingStepperView/OnboardingStepView.js
  src/components/OnboardingStepperView/index.js
  src/components/RootNavigator/BaseOnboardingNavigator.js
  src/components/SelectDevice/index.js
  src/components/SupportLinkError.js
  src/components/ValidateOnDevice.js
  src/config/urls.js
  src/families/polkadot/BondFlow/02-Amount.js
  src/families/polkadot/TransactionConfirmFields.js
  src/families/polkadot/operationDetails.js
  src/index.js
  src/languages.js
  src/locales/en/common.json
  src/locales/fr/common.json
  src/logic/terms.js
  src/screens/Account/SubAccountsList.js
  src/screens/Onboarding/OnboardingQuiz.js
  src/screens/Onboarding/steps/language.js
  src/screens/Onboarding/steps/newDeviceInfo.js
  src/screens/Onboarding/steps/terms.js
  src/screens/Onboarding/steps/welcome.js
  src/screens/OperationDetails/Content.js
  src/screens/Settings/General/ThemeSettingsRow.js
  yarn.lock
Labels: QA, important
