Repository LedgerHQ/ledger-live-mobile, pull requests merged in 2021-04, with the labels that each got.

#1651 LL-5120 LL-5129 fix Onboarding end navigation issue
  src/screens/Onboarding/steps/finish.js
Labels: QA

#1660 LL-5184 (NotificationCenter): fix link issue
  index.js
  package.json
  src/screens/NotificationCenter/NewsRow.js
  yarn.lock
Labels: bug, important

#1657 LL-5072 (Chain type): updated wording
  src/locales/en/common.json
  src/screens/AddAccounts/03-Accounts.js
Labels: QA

#1640 LL-4780 (Icons): update
  android/app/src/main/assets/fonts/FontAwesome5_Brands.ttf
  android/app/src/main/assets/fonts/FontAwesome5_Regular.ttf
  android/app/src/main/assets/fonts/FontAwesome5_Solid.ttf
  package.json
  src/components/CircleCurrencyIcon.js
  src/components/CurrencyIcon.js
  src/screens/Manager/AppsList/AppIcon.js
  src/screens/Manager/AppsList/AppRow.js
  src/screens/Manager/Modals/AppDependenciesModal.js
  src/screens/Manager/Modals/SearchModal.js
  src/screens/Manager/Modals/UninstallDependenciesModal.js
  src/screens/Manager/Modals/UpdateAllModal.js
  yarn.lock
Labels: QA, important

#1654 LL-4626 - Add the possibility to retrieve latest log in mobile app
  index.js
  src/components/GenericErrorView.js
  src/locales/en/common.json
  src/log-report.js
  src/screens/DebugLogs.js
Labels: QA
