Repository LedgerHQ/ledger-live-mobile, pull requests merged in 2021-05, with the labels that each got.

#1684 LL-5306 (Analytics): add currencyName to send/receive flow page events
  src/screens/ReceiveFunds/02-ConnectDevice.js
  src/screens/ReceiveFunds/03-Confirmation.js
  src/screens/SendFunds/02-SelectRecipient.js
  src/screens/SendFunds/03-Amount.js
  src/screens/SendFunds/04-Summary.js
  src/screens/SendFunds/07-ValidationError.js
  src/screens/SendFunds/07-ValidationSuccess.js
Labels: QA

#1681 Live common 19.7.x
  ios/ledgerlivemobile.xcodeproj/project.pbxproj
  package.json
  src/actions/general.js
  src/actions/portfolio.js
  src/actions/settings.js
  src/components/AccountGraphCard.js
  src/components/AssetGraphCard.js
  src/components/CounterValue.js
  src/components/CurrencyUnitValue.js
  src/components/Delta.js
  src/components/DeviceAction/index.js
  src/components/FormatDate.js
  src/components/Graph/types.js
  src/components/GraphCard.js
  src/components/NetworkFeeInfo.js
  src/components/Pills.js
  src/components/ProgressBar.js
  src/components/SelectFeesStrategy.js
  src/components/SendRowsFee.js
  src/const/navigation.js
  src/experimental.js
  src/families/bitcoin/BitcoinFeePerByteRow.js
  src/families/bitcoin/ScreenEditCustomFees.js
  src/families/bitcoin/ScreenEditFeePerByte/CustomFeesRow.js
  src/families/bitcoin/ScreenEditFeePerByte/FeesRow.js
  src/families/bitcoin/ScreenEditFeePerByte/index.js
  src/families/bitcoin/SendRowsFee.js
  src/families/bitcoin/index.js
  src/families/ethereum/EditFeeUnitEthereum.js
  src/families/ethereum/EthereumCustomFees.js
  src/families/ethereum/EthereumFeeRow.js
  src/families/ethereum/EthereumFeesStrategy.js
  src/families/ethereum/ScreenEditFee.js
  src/families/ethereum/ScreenEditGasLimit.js
  src/families/ethereum/SendRowGasLimit.js
  src/families/ethereum/SendRowsFee.js
  src/families/ethereum/index.js
  src/locales/en/common.json
  src/logic/compareDate.js
  src/reducers/settings.js
  src/screens/Account/ListHeaderComponent.js
  src/screens/Asset/index.js
  src/screens/Distribution/DistributionCard.js
  src/screens/Distribution/index.js
  src/screens/Portfolio/AnimatedTopBar.js
  src/screens/Portfolio/BalanceHeader.js
  src/screens/Portfolio/GraphCardContainer.js
  src/screens/Portfolio/StickyHeader.js
  src/screens/SendFunds/03-Amount.js
  src/screens/SendFunds/04-Summary.js
  yarn.lock
Labels: important

#1691 (Portfolio): fix range graph buttons regression + graph colors
  src/components/AccountGraphCard.js
  src/components/AssetGraphCard.js
  src/components/GraphCard.js
  src/screens/Portfolio/index.js
Labels: bug, important
