Repository LedgerHQ/ledger-live-mobile, pull requests merged in 2021-03, with the labels that each got.

#1599 LL-4639 (Lending) crash issue
  src/screens/Account/LendingBanners.js
Labels: QA

#1567 LL-1944 Fix iOS/Android sharing in general
  android/app/src/main/AndroidManifest.xml
  ios/Podfile.lock
  package.json
  src/screens/DebugLogs.js
  yarn.lock
Labels: QA

#1616 live-common 18.6.0 + 18.7.0 + libcore
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: QA, important

#1619 LL-4509 Fix spinner on account screen
  src/components/accountSyncRefreshControl.js
Labels: QA

#1618 LL-4771 Fix sorting for currency selector
  src/components/FilteredSearchBar.js
Labels: QA

#1602 LL-4311 (Send): paste address scroll issue
  src/screens/SendFunds/02-SelectRecipient.js
Labels: QA

#1614 [LL-4684] DOT remove fee fields confirmation
  src/families/polkadot/TransactionConfirmFields.js
Labels: QA

#1615 [LL-4685] DOT: Remove CTA navigation on error
  src/families/polkadot/BondFlow/index.js
  src/families/polkadot/NominateFlow/index.js
  src/families/polkadot/RebondFlow/index.js
  src/families/polkadot/SimpleOperationFlow/index.js
  src/families/polkadot/UnbondFlow/index.js
Labels: QA

#1600 LL-4604 navigation crash issue
  src/index.js
  src/rootnavigation.js
  src/screens/WalletConnect/Provider.js
Labels: QA

#1603 LL-4290 (Onboarding): fix font style in help modal desc
  src/components/OnboardingStepperView/OnboardingInfoModal.js
Labels: QA

#1607 LL-4699 (Language) fix long text issue on onboarding
  src/actions/settings.js
  src/components/AnimatedHeader.js
  src/context/Locale.js
  src/reducers/settings.js
  src/screens/Settings/General/LanguageRow.js
  src/screens/Settings/General/index.js
Labels: QA

#1620 fix(AccountActions): wait BottomModal hide before navigate to avoid kb blur - LL-4696
  src/screens/Account/AccountActions.js
Labels: QA

#1604 LL-4520 (Modals): block opening two modals at same time
  src/components/BottomModal.js
Labels: QA

#1630 live-common 18.8.x
  ios/Podfile.lock
  package.json
  src/components/AccountCard.js
  src/components/Button.js
  src/components/CheckBox.js
  src/components/SelectableAccountsList.js
  src/config/urls.js
  src/locales/en/common.json
  src/screens/AddAccounts/01-SelectCrypto.js
  src/screens/AddAccounts/02-SelectDevice.js
  src/screens/AddAccounts/02-TokenCurrencyDisclaimer.js
  src/screens/AddAccounts/03-Accounts.js
  src/screens/AddAccounts/AddAccountsModal.js
  src/screens/Settings/General/ThemeSettingsRow.js
  yarn.lock
Labels: important

#1621 LL-4585 - Add buy coins
  src/screens/Exchange/coinifyConfig.js
Labels: QA

#1622 LL-4754 - no more oops
  src/locales/en/common.json
Labels: QA

#1637 (Terms): fix some issue in the markdown
  TERMS.es.md
  TERMS.fr.md
  TERMS.md
  TERMS.ru.md
Labels: bug

#1633 [LL-4432] (PrivacyPolicy): add translated url for privacy policy
  TERMS.es.md
  TERMS.ru.md
  src/config/urls.js
  src/languages.js
  src/screens/Onboarding/steps/terms.js
  src/screens/Settings/About/PrivacyPolicyRow.js
Labels: QA, important

#1596 LL-4548 LL-4551 Notification Center
  src/colors.js
  src/components/Delta.js
  src/components/ExternalLink.js
  src/components/FormatDate.js
  src/components/RootNavigator/BaseNavigator.js
  src/components/RootNavigator/NotificationCenterNavigator.js
  src/components/Touchable.js
  src/config/urls.js
  src/const/navigation.js
  src/db.js
  src/icons/Bell.js
  src/icons/WarningOutline.js
  src/index.js
  src/locales/en/common.json
  src/screens/NotificationCenter/News.js
  src/screens/NotificationCenter/NewsRow.js
  src/screens/NotificationCenter/NotificationsProvider.js
  src/screens/NotificationCenter/Snackbar/Snackbar.js
  src/screens/NotificationCenter/Snackbar/SnackbarContainer.js
  src/screens/NotificationCenter/Status.js
  src/screens/Portfolio/Header.js
  src/screens/Settings/Debug/GenerateAnnouncementMockData.js
  src/screens/Settings/Debug/ToggleMockStatusIncident.js
  src/screens/Settings/Debug/index.js
  src/screens/Settings/index.js
Labels: QA, important

#1636 LL-4972 (Manager): filter modal auto-closing issue
  src/components/BottomModal.js
Labels: bug

#1643 COIN-1440 fixes via live-common bump
  yarn.lock
Labels: important

#1610 LL-4579 (Theme): track os theme and change app theme accordingly
  app.json
  ios/ledgerlivemobile/Info.plist
  src/actions/settings.js
  src/index.js
  src/reducers/settings.js
Labels: QA

#1611 LL-4447 Floating rate support for swap
  android/app/src/main/assets/fonts/FontAwesome5_Brands.ttf
  android/app/src/main/assets/fonts/FontAwesome5_Pro_Brands.ttf
  android/app/src/main/assets/fonts/FontAwesome5_Pro_Light.ttf
  android/app/src/main/assets/fonts/FontAwesome5_Pro_Regular.ttf
  android/app/src/main/assets/fonts/FontAwesome5_Pro_Solid.ttf
  android/app/src/main/assets/fonts/FontAwesome5_Regular.ttf
  android/app/src/main/assets/fonts/FontAwesome5_Solid.ttf
  assets/fonts/FontAwesome5_Pro_Brands.ttf
  assets/fonts/FontAwesome5_Pro_Light.ttf
  assets/fonts/FontAwesome5_Pro_Regular.ttf
  assets/fonts/FontAwesome5_Pro_Solid.ttf
  ios/ledgerlivemobile.xcodeproj/project.pbxproj
  ios/ledgerlivemobile/Info.plist
  package.json
  src/components/CountdownTimer.js
  src/components/CurrencyInput.js
  src/components/DeviceAction/rendering.js
  src/components/InfoModal.js
  src/components/ToggleButton.js
  src/components/TooltipLabel.js
  src/components/useInterval.js
  src/families/tron/VoteFlow/02-VoteModal.js
  src/locales/en/common.json
  src/locales/es/common.json
  src/locales/fr/common.json
  src/locales/ja/common.json
  src/locales/ko/common.json
  src/locales/ru/common.json
  src/locales/zh/common.json
  src/reducers/settings.js
  src/screens/Account/hooks/useActions.js
  src/screens/Swap/Confirmation.js
  src/screens/Swap/Form/Amount.js
  src/screens/Swap/Form/Rate.js
  src/screens/Swap/Form/Summary/SummaryBody.js
  src/screens/Swap/Form/Summary/index.js
  src/screens/Swap/Form/index.js
  src/screens/Swap/OperationDetails.js
  src/screens/Swap/SwapStatusIndicator.js
  yarn.lock
Labels: QA, important

#1650 fix flattenedSwapSupportedCurrenciesSelector issue
  src/reducers/settings.js
Labels: QA, important
