Repository LedgerHQ/ledger-live-mobile, pull requests merged in 2022-03, with the labels that each got.

#2260 LIVE-1599 - Fix bottom drawer inconsistencies
  ios/Podfile.lock
  ios/ledgerlivemobile.xcodeproj/project.pbxproj
  src/components/BottomModal.tsx
  src/components/DelegationDrawer.js
  src/components/DeviceActionModal.js
  src/components/DeviceJob/StepRunnerModal.js
  src/components/EditFeeUnit.js
  src/components/FirmwareUpdateBanner.js
  src/components/GenericErrorBottomModal.js
  src/components/Nft/NftLinksPanel.js
  src/components/WebPlatformPlayer/InfoPanel.js
  src/families/polkadot/components/NominationDrawer.js
  src/families/tezos/DelegationDetailsModal.js
  src/families/tron/VoteFlow/02-VoteModal.js
  src/screens/Platform/DAppDisclaimer.js
  src/screens/ReceiveFunds/03-Confirmation.js
  yarn.lock
Labels: HODL

#2271 Revert "LIVE-1413 - Hide tab bar when keyboard focus on market page"
  src/components/RootNavigator/MainNavigator.js
Labels: important

#2257 LIVE-1468 Prevent useless rerenders on NFT Gallery
  android/app/build.gradle
  android/app/src/debug/java/com/ledger/live/ReactNativeFlipper.java
  android/settings.gradle
  package.json
  src/components/Button.js
  src/components/LText/index.js
  src/components/Nft/NftCard.js
  src/components/OperationRow.js
  src/components/Skeleton.js
  src/screens/Nft/NftGallery/NftCollectionWithName.js
  yarn.lock
Labels: feature-ready

#2261 LIVE-1601 Use FastImage component for all platforms
  src/components/Nft/NftImage.js
  src/components/Nft/NftViewer.js
Labels: feature-ready

#2312 LIVE-1712 create user buy screen
  src/icons/DropdownArrow.js
  src/locales/en/common.json
  src/screens/Exchange/Buy.js
  src/screens/Exchange/BuyOption.js
  src/screens/Exchange/ProviderBullet.js
  src/screens/Exchange/SelectAccount.js
  src/screens/Exchange/SelectCurrency.js
Labels: Work in progress

#2328 LIVE-1748 Prevent crash when using proxy device
  src/components/DeviceAction/getDeviceAnimation.js
Labels: important, feature-ready

#2320 New Crowdin updates
  src/locales/ja/common.json
Labels: feature-ready

#2304 tezos js: Fixes NotEnoughBalance errors to display + Activate Tezos
  package.json
  src/experimental.js
  src/families/index.js
  src/screens/OperationDetails/Extra.js
  yarn.lock
Labels: feature-ready

#2277 LIVE-1443 LIVE-1170 react-native-fact-crypto added
  android/app/src/main/java/com/ledger/live/MainApplication.java
  android/settings.gradle
  ios/Podfile.lock
  package.json
  src/live-common-setup.js
  src/logic/secp256k1.js
  yarn.lock
Labels: feature-ready

#2274 LIVE-1534 Enable Celo to production
  src/live-common-setup.js
Labels: feature-ready

#2104 LL-8866 - Add PanAndZoom view to NFTs
  src/components/Nft/NftImage.js
  src/components/Nft/NftImageViewer.js
  src/components/Nft/NftViewer.js
  src/components/PanAndZoomView.js
  src/components/RootNavigator/BaseNavigator.js
  src/components/RootNavigator/NftNavigator.js
  src/const/navigation.js
  src/screens/OperationDetails/index.js
Labels: feature-ready
