Repository LedgerHQ/ledger-live-mobile, pull requests merged in 2022-05, with the labels that each got.

#2459 LIVE-2142 - Add "stake" button to account page actions
  src/families/cosmos/accountActions.tsx
  src/families/polkadot/accountActions.js
  src/families/tezos/DelegationFlow/Started.tsx
  src/families/tezos/accountActions.tsx
  src/families/tron/accountActions.js
Labels: feature-ready

#2363 [LIVE-1174] - Feature: Upgrade NFT Architecture LLM V3
  src/components/Nft/NftCard.tsx
  src/components/Nft/NftCollectionRow.tsx
  src/components/Nft/NftImage.tsx
  src/components/Nft/NftImageViewer.tsx
  src/components/Nft/NftLinksPanel.tsx
  src/components/Nft/NftViewer.tsx
  src/components/OperationRowNftName.tsx
  src/components/RootNavigator/BaseNavigator.tsx
  src/components/RootNavigator/NftNavigator.tsx
  src/components/Skeleton.tsx
  src/locales/en/common.json
  src/screens/Account/NftCollectionsList.tsx
  src/screens/Nft/NftCollection/NftCollectionHeaderTitle.tsx
  src/screens/Nft/NftCollection/index.tsx
  src/screens/Nft/NftGallery/NftCollectionWithName.tsx
  src/screens/Nft/NftGallery/NftGalleryHeaderTitle.tsx
  src/screens/Nft/NftGallery/index.tsx
  src/screens/OperationDetails/Content.js
  src/screens/SendFunds/01b-SelectCollection.tsx
  src/screens/SendFunds/01c-SelectNft.tsx
  src/screens/SendFunds/02-SelectRecipient.js
  src/screens/SendFunds/03b-AmountNft.tsx
  src/screens/SendFunds/04-Summary.js
  src/screens/SendFunds/SummaryNft.tsx
  yarn.lock
Labels: feature-ready

#2429 LIVE-1819 FTS Support
  src/screens/Manager/Device/index.tsx
  src/screens/PairDevices/Scanning.tsx
  yarn.lock
Labels: feature-ready

#2440 LIVE-1774 LIVE-1927 - Add Spanish (ES) and Chinese (ZH) to fully supported languages
  src/languages.js
Labels: feature-ready

#2452 Feat/live 1625 hide nft collection v3 rebased
  package.json
  src/actions/settings.js
  src/components/Nft/NftCollectionOptionsMenu.tsx
  src/components/Nft/NftCollectionRow.tsx
  src/components/RootNavigator/SettingsNavigator.tsx
  src/components/Touchable.js
  src/const/navigation.js
  src/locales/en/common.json
  src/reducers/settings.js
  src/screens/Account/ListHeaderComponent.tsx
  src/screens/Account/NftCollectionsList.tsx
  src/screens/Nft/NftGallery/NftCollectionWithName.tsx
  src/screens/Nft/NftGallery/index.tsx
  src/screens/SendFunds/01b-SelectCollection.tsx
  src/screens/SendFunds/01c-SelectNft.tsx
  src/screens/Settings/Accounts/HiddenNftCollections.tsx
  src/screens/Settings/Accounts/index.tsx
  yarn.lock
Labels: dependencies, feature-ready

#2500 Ignore more errors to be sent to Sentry
  index.js
Labels: important
